# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-18 18:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flower',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('color', models.CharField(max_length=64)),
                ('description', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Garden',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('description', models.TextField(default='')),
            ],
        ),
        migrations.AddField(
            model_name='flower',
            name='garden',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sunflower.Garden'),
        ),
    ]
