# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-18 18:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sunflower', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flower',
            name='garden',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='sunflower.Garden'),
        ),
    ]
